[package]
name = "tetris"
version = "0.1.0"
authors = ["Martin Baumgart <martin.baumgart@daparto.com>"]
edition = "2018"

[dependencies]
piston_window = "0.99.0"
piston2d-sprite = "0.55.0"
piston-ai_behavior = "0.31.0"
find_folder = "0.3.0"